version: 0.0
os: windows
files:
  - source: app
    destination: c:\inetpub\wwwroot
hooks:
    BeforeInstall:
      - location: \deploy-scripts\before-install.sh
        timeout: 150
        runas: Administrator